// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import AppointmentFormController from "./appointment_form_controller"
application.register("appointment-form", AppointmentFormController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import HorariosController from "./horarios_controller"
application.register("horarios", HorariosController)
